#!/bin/sh
is_first_boot=$(uci -q get zz_config.@status[0].first_boot)
if test "$is_first_boot" -gt "0"; then
  #echo -e "m28cm28c\nm28cm28c" | (passwd root)
  uci set system.@system[0].hostname='zzM28C'
  uci commit system
  uci del dhcp.lan.dhcpv6
  uci set dhcp.lan.ra_flags='none'
  uci set network.lan.ipaddr='192.168.28.1'
  uci add_list network.lan.ip6class='4_1_2v6'
  uci set cpufreq.global.set='1'
  uci commit
  /etc/init.d/network reload
  uci set wireless.radio0.cell_density='0'
  uci set wireless.radio0.country='CN'
  uci set wireless.default_radio0.ssid='zzM28C'
  uci set wireless.default_radio0.encryption='sae-mixed'
  uci set wireless.default_radio0.key='m28cm28c'
  uci commit wireless
  /etc/init.d/network reload
  wifi
  uci -q set zz_config.@status[0].first_boot=0
  uci commit zz_config
fi

sed -i "s?set wireless\.default_radio\${devidx}\.ssid=LEDE?set wireless\.default_radio\${devidx}\.ssid=\'zzM28C\'?g" /lib/wifi/mac80211.sh
sed -i "s?set wireless\.default_radio\${devidx}\.encryption=none?set wireless\.default_radio\${devidx}\.encryption=\'psk2+ccmp\'\n\t\t\tset wireless\.default_radio\${devidx}\.key=\'m28cm28c\'?g" /lib/wifi/mac80211.sh
uci commit
